config/routes.rb
Rails.application.routes.draw do

  root 'invoices#index'
  resources :invoices, only: [:index, :show, :edit, :update, :create]
  post 'invoice/upload_file', to: 'invoices#upload_file', as: 'upload_invoice'
  resources :collections, only: [:index, :show, :edit, :update, :create]
  post 'collection/collection_file', to: 'collections#collection_file', as: 'upload_collection'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :collection
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :bill, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.all.group_by(&:bill_id)
  end

  def create

  end

  def collection_path
    if params[:file].present?
      @data.each do |data|
        @invoice = Bill.find_by(reference: data['referbundle installence'])
        if @invoice.present?
          Collection.find_or_create_by(bill_id: @invoice.id,
                                       amount: data['amount'],
                                       reference: data['reference'],
                                       collection_date: data['collection_date'],
          )
        else
          Collection.find_or_create_by(bill_id: nil,
                                       amount: data['amount'],
                                       reference: data['reference'],
                                       collection_date: data['collection_date'],
          )
        end
      end
    end
  end

  private

  def set_collection
    @collection = Collection.find_by(id: params[:id])
  end

  def collection_params
    params.require(:collection).permit(:collection_date, :amount, :reference)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_invoice, only: [:show, :edit]

  def index
    @invoices = Bill.all
  end

  def edit

  end

  def show

  end

  def create
    @invoice = Bill.new(invoice_params)
    if @invoice.save
      flash[:success] = "successful"
    else
      flash[:error] = @invoice.errors.full_messages.to_sentence
    end
  end

  def update
    @invoice.update(invoice_params)
  end

  def upload_file
    if params[:file].present?
      @data = JSON.parse(File.open(params[:file].tempfile).read)
      @data.each do |data|
        Bill.find_or_create_by(
            brand_manager: data['brand_manager'],
            narration: data['narration'],
            invoice_date: data['invoice_date'],
            amount: data['amount'],
            customer_name: data['customer_name'],
            reference: data['reference']
        )
      end

    end
  end

  private

  def set_invoice
    @invoice = Bill.find_by(id: params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:brand, :narration, :invoice_date, :amount, :customer_name, :reference)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/collections/index.html.erb
<%= form_with url: collection_path, method: :post, multipart: true do |f| %>
  <div class="file has-name is-fullwidth">
    <label class="file-label">
      <%= f.file_field 'file', class: 'file-input' %>
      <span class="file-cta">
                <span class="file-icon">
                  <%= icon 'fas', 'upload' %>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
      <span class="file-name">
              </span>
    </label>
    <%= f.submit 'Upload', class: 'button is-primary is-small ' %>
  </div>
<% end %>
<% if @collections.present? %>
  <% @collections.each do |bill, collections| %>
    <p><%= bill.bill.brand_manager %></p>
    <% collections.each do |collection|%>
      <table class="table">
        <thead>
        <tr>
          <th>Reference</th>
          <th>Amount</th>
          <th>Date</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= collection.reference %></td>
          <td><%= collection.amount %></td>
          <td><%= collection.collection_date %></td>
        </tr>
        </tbody>
      </table>
    <% end %>
  <% end %>
<% else %>
  <p>There are no collection found</p>
<% end %>

app/views/invoices/_invoices.html.erb
<% if invoices.present? %>
  <table class="table">
    <thead>
    <tr>
      <th>Reference</th>
      <th>Invoice Date</th>
      <th>Customer Name</th>
      <th>Brand Manager</th>
      <th>Narration</th>
      <th>Amount</th>
      <th>Total Collection</th>
      <th>Balance</th>
      <th>Edit</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% invoices.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.reference, invoice_path(invoice.id), method: :get %></td>
        <td><%= invoice.invoice_date %></td>
        <td><%= invoice.customer_name %></td>
        <td><%= invoice.brand_manager %></td>
        <td><%= invoice.narration %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.collection.sum(&:amount) %></td>
        <td><%= invoice.amount - invoice.collection.sum(&:amount) %></td>
        <td>
          <%= link_to edit_invoice_path(invoice), class: 'button is-primary is-outlined is-small', method: :get do %>
            <% icon('fas', 'edit') %>
          <% end %>
        </td>
        <td><%= link_to 'Add collection', collections_path, class: 'button is-primary is-outlined is-small  ', method: :post %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="has-text-centered">There are no Bills found</p>
<% end %>

app/views/invoices/edit.html.erb
<% form_with model: Invoice do |f| %>
  <div class="field">
    <label class="label">Brand Manager</label>
    <p class="control">
        <span class="select">
         <%= f.text_field :brand_manager, @invoice.brand_manager, class: 'input', required: true %>
         </span>
    </p>
  </div>
  <div class="field">
    <label class="label">Narration</label>
    <p class="control">
        <span class="select">
         <%= f.text_field :brand_manager, @invoice.narration, class: 'input', required: true %>
         </span>
    </p>
  </div>
  <div class="field">
    <label class="label">Invoice Date</label>
    <p class="control">
        <span class="select">
         <%= f.text_field :brand_manager, @invoice.invoice_date, class: 'input', required: true %>
         </span>
    </p>
  </div>
  <div class="field">
    <label class="label">Amount</label>
    <p class="control">
        <span class="select">
         <%= f.text_field :brand_manager, @invoice.amount, class: 'input', required: true %>
         </span>
    </p>
  </div>
  <div class="field">
    <label class="label">Customer Name</label>
    <p class="control">
        <span class="select">
         <%= f.text_field :brand_manager, @invoice.customer_name, class: 'input', required: true %>
         </span>
    </p>
  </div>
  <div class="field">
    <label class="label">Reference</label>
    <p class="control">
        <span class="select">
         <%= f.text_field :brand_manager, @invoice.reference, class: 'input', required: true %>
         </span>
    </p>
  </div>
<% end %>

app/views/invoices/index.html.erb
<%= form_with url: upload_invoice_path, method: :post, multipart: true do |f| %>
  <div class="file has-name is-fullwidth">
    <label class="file-label">
      <%= f.file_field 'file', class: 'file-input' %>
      <span class="file-cta">
                <span class="file-icon">
                  <%= icon 'fas', 'upload' %>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
      <span class="file-name">
              </span>
    </label>
    <%= f.submit 'Upload', class: 'button is-primary is-small ' %>
  </div>
  <div class="field has-addons">
    <%= link_to 'show pending bill', invoices_path(type: 'pending'), class: 'button is-primary is-small', data: {remote: true} %>
    <%= link_to 'show collected bill', invoices_path(type: 'collected'), class: 'button is-primary is-small', data: {remote: true} %>
  </div>
<% end %>
<div data-behaviour="table">
  <%= render partial: 'invoices', locals: {invoices: @invoices} %>
</div>

app/views/invoices/index.js.erb
$('[data-behaviour="table"]').html('<%= j render 'invoices', locals: {invoices: @invoices} %>')

app/views/invoices/show.html.erb
<table class="table">
  <tr>
    <th>Reference</th>
    <td><%=@invoice.reference %></td>
  </tr>
  <tr>
    <th>Invoice Date</th>
    <td><%=@invoice.invoice_date %></td>
  </tr>
  <tr>
    <th>Customer Name</th>
    <td><%=@invoice.customer_name %></td>
  </tr>
  <tr>
    <th>Brand Manager</th>
    <td><%=@invoice.brand_manager %></td>
  </tr>
  <tr>
    <th>Narration</th>
    <td><%=@invoice.narration %></td>
  </tr>
  <tr>
    <th>Amount</th>
    <td><%=@invoice.amount %></td>
  </tr>
  <tr>
    <th>
    </th>
    <td><%= link_to 'back', invoices_path, class: 'button is-small is-info is-outlined' %></td>
  </tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="box has-text-centered" style="margin: auto; width: 75rem; margin-top: 150px;">
    <%= yield %>
  </div>
  </body>
</html>